// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj3SbZaEwBme942AH_8J_RecXym0oXD74',
    appId: '1:632471526230:web:db7a43927efecae05fd4f7',
    messagingSenderId: '632471526230',
    projectId: 'community-assistance-b9e1e',
    authDomain: 'community-assistance-b9e1e.firebaseapp.com',
    storageBucket: 'community-assistance-b9e1e.firebasestorage.app',
    measurementId: 'G-BCX6C2W619',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaZ7KpnxKFQgPs7gMbrnkF-cl3HCHvUVg',
    appId: '1:632471526230:android:56fb39cd170cef375fd4f7',
    messagingSenderId: '632471526230',
    projectId: 'community-assistance-b9e1e',
    storageBucket: 'community-assistance-b9e1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ekMzdlONI6K2OXhUJRUdXykbudGKs2A',
    appId: '1:632471526230:ios:8790bbbd1d1d3c645fd4f7',
    messagingSenderId: '632471526230',
    projectId: 'community-assistance-b9e1e',
    storageBucket: 'community-assistance-b9e1e.firebasestorage.app',
    iosBundleId: 'com.masti.communityAssistance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ekMzdlONI6K2OXhUJRUdXykbudGKs2A',
    appId: '1:632471526230:ios:8790bbbd1d1d3c645fd4f7',
    messagingSenderId: '632471526230',
    projectId: 'community-assistance-b9e1e',
    storageBucket: 'community-assistance-b9e1e.firebasestorage.app',
    iosBundleId: 'com.masti.communityAssistance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj3SbZaEwBme942AH_8J_RecXym0oXD74',
    appId: '1:632471526230:web:5fe8d46f73645fa85fd4f7',
    messagingSenderId: '632471526230',
    projectId: 'community-assistance-b9e1e',
    authDomain: 'community-assistance-b9e1e.firebaseapp.com',
    storageBucket: 'community-assistance-b9e1e.firebasestorage.app',
    measurementId: 'G-99T7BQLDS0',
  );
}
